
# Site settings
title: Git Cooking
description: > # this means to ignore newlines until "baseurl:"
  A recipe manager.
baseurl: "/Git-Cooking"
url: "https://guinane.xyz"

# Markdown settings
markdown: kramdown

defaults:
  - scope:
      path: "_posts/meals"
      type: posts
    values:
      permalink: meals/:title
      layout: post
      category: meals
      select: meals
  - scope:
      path: "_posts/drinks"
      type: posts
    values:
      permalink: drinks/:title
      layout: post
      category: drinks
      select: drinks
  - scope:
      path: "_posts/treats"
      type: posts
    values:
      permalink: treats/:title
      layout: post
      category: treats
      select: treats

# Sass settings
sass:
  add_charset: true
  sass_dir: assets/sass
  style: :compressed

# Build settings
exclude:
  - package.json
  - README.md
  - CNAME
  - assets/sass

# Plugin settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
